import * as THREE from "three";
const planets_data = [
  {
    id: 1,
    textureUrl: "",
    position: new THREE.Vector3(1.5, 0, 0),
    args: [0.08, 16, 16] as [number, number, number],
    snipingSpeed: 0.06,
    rotationSpeed: -1,
    distanceFromSun: 1.5,
    name: "Mercury",
    hasTexture: false,
    color: "#b1b1b1",
  },
  {
    id: 2,
    textureUrl: "",
    position: new THREE.Vector3(2, 0, 0),
    args: [0.09, 32, 32] as [number, number, number],
    snipingSpeed: 0.03,
    rotationSpeed: -0.3,
    distanceFromSun: 11,
    name: "Pluton",
    hasTexture: false,
    color: "#deb887",
  },
  {
    id: 3,
    textureUrl: "",
    position: new THREE.Vector3(2.5, 0, 0),
    args: [0.07, 16, 16] as [number, number, number],
    snipingSpeed: 0.005,
    rotationSpeed: 0.1,
    distanceFromSun: 2.5,
    name: "Moon",
    hasTexture: false,
    color: "#c0c0c0",
  },
  {
    id: 4,
    textureUrl: "earth_color_10K-min.png",
    position: new THREE.Vector3(3.5, 0, 0),
    args: [0.1, 16, 16] as [number, number, number],
    snipingSpeed: 0.009,
    rotationSpeed: 0.2,
    distanceFromSun: 3.5,
    name: "Earth",
    hasTexture: true,
    color: "",
  },
  {
    id: 5,
    textureUrl: "",
    position: new THREE.Vector3(4, 0, 0),
    args: [0.09, 16, 16] as [number, number, number],
    snipingSpeed: 0.03,
    rotationSpeed: 5,
    distanceFromSun: 4,
    name: "Mars",
    hasTexture: false,
    color: "#b22222",
  },
  {
    id: 6,
    textureUrl:
      "jupiter_hubble__december_2016__by_mrspace43_celestia_dfjnznc-min.png",
    position: new THREE.Vector3(5, 0, 0),
    args: [0.7, 32, 32] as [number, number, number],
    snipingSpeed: 0.004,
    rotationSpeed: 1,
    distanceFromSun: 5,
    name: "Jupiter",
    hasTexture: true,
    color: "",
  },
  {
    id: 7,
    textureUrl: "saturn_texture_map_by_neptuneproproduction_dcaift0-min.jpg",
    position: new THREE.Vector3(7.5, 0, 0),
    args: [0.5, 16, 16] as [number, number, number],
    snipingSpeed: 0.0007,
    rotationSpeed: 0.8,
    distanceFromSun: 7.5,
    name: "Saturn",
    hasTexture: true,
    color: "",
  },
  {
    id: 8,
    textureUrl: "",
    position: new THREE.Vector3(8.5, 0, 0),
    args: [0.1, 16, 16] as [number, number, number],
    snipingSpeed: 0.0002,
    rotationSpeed: 0.5,
    distanceFromSun: 8.5,
    name: "Uranus",
    hasTexture: false,
    color: "#afeeee",
  },
  {
    id: 9,
    textureUrl: "",
    position: new THREE.Vector3(10, 0, 0),
    args: [0.1, 8, 8] as [number, number, number],
    snipingSpeed: 0.0002,
    rotationSpeed: 0.5,
    distanceFromSun: 10,
    name: "Neptune",
    hasTexture: false,
    color: "#4682b4",
  },
];

export default planets_data;
